package com.bmpl.myfirstapp;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;

public class MainActivity extends AppCompatActivity implements View.OnClickListener{

    //instance variables declared
    Button clickButton, clearButton;

    TextView textView;

    @Override
    protected void onCreate(Bundle b) {
        super.onCreate(b);//parent functionality call
        //R is auto generated class which is generated by android for every project--> R.java--> store all the ids required to run the project
        setContentView(R.layout.activity_main);//binding of xml file with the java file

        //Step-1: Downcasting
        //Null pointer exception
        //                              int
        clickButton = (Button) findViewById(R.id.button);
        clearButton = (Button)findViewById(R.id.clearButton);
        textView = (TextView)findViewById(R.id.welcomeTextView);

        //event handling--> event listeners--> event fire and event handlers--> handle the fired event
        //Step-2: Attach listener
        //Step-3: Handler--> different ways--> by using anonymous  interface--> no name

        //short way to access handler--> When we have lesser no of buttons
        /*clickButton.setOnClickListener(new View.OnClickListener() {

            @Override
            public void onClick(View view) {//event handler
                textView.setText("You clicked Again");
            }
        });

        clearButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

            }
        });*/

        //attach listener
        clickButton.setOnClickListener(this);
        clearButton.setOnClickListener(this);

    }
    //2nd way of using handler

    @Override
    public void onClick(View view)
    {
        //clear or click
        switch (view.getId()){
            //click
            case R.id.button:
                textView.setText("You clicked Again");
                break;

            case R.id.clearButton:
                textView.setText("");
                break;

        }
    }
}